// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Lgk52O9i21ouXdHWx6uVuWpb_rCORBM',
    appId: '1:809488755140:web:8e56459906c1a9e2249c91',
    messagingSenderId: '809488755140',
    projectId: 'al-tareeq',
    authDomain: 'al-tareeq.firebaseapp.com',
    storageBucket: 'al-tareeq.appspot.com',
    measurementId: 'G-R7RNHCZYRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQTkoEf0JvJ37j9jiUOJxGysA5up1bNs',
    appId: '1:809488755140:android:cd3bf34b96099942249c91',
    messagingSenderId: '809488755140',
    projectId: 'al-tareeq',
    storageBucket: 'al-tareeq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWz0-bN3GHh0hFJveiS9Ni9BLQg6xU-g',
    appId: '1:809488755140:ios:66a897feb6da64f9249c91',
    messagingSenderId: '809488755140',
    projectId: 'al-tareeq',
    storageBucket: 'al-tareeq.appspot.com',
    iosBundleId: 'com.example.tareeq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUWz0-bN3GHh0hFJveiS9Ni9BLQg6xU-g',
    appId: '1:809488755140:ios:66a897feb6da64f9249c91',
    messagingSenderId: '809488755140',
    projectId: 'al-tareeq',
    storageBucket: 'al-tareeq.appspot.com',
    iosBundleId: 'com.example.tareeq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Lgk52O9i21ouXdHWx6uVuWpb_rCORBM',
    appId: '1:809488755140:web:54745dfbe40b6d82249c91',
    messagingSenderId: '809488755140',
    projectId: 'al-tareeq',
    authDomain: 'al-tareeq.firebaseapp.com',
    storageBucket: 'al-tareeq.appspot.com',
    measurementId: 'G-RR2H6LMZDP',
  );
}
